INSERT INTO PRODUCTS (ID, NAME, DESCRIPTION, PRICE)
    VALUES (1, 'ABAJUR', 'ABAJUR COMUN', 12.34);
    
INSERT INTO PRODUCTS (ID, NAME, DESCRIPTION, PRICE)
    VALUES (2, 'ASPIRADOR', 'ASPIRADOR DE PO', 98.50);
    
INSERT INTO PRODUCTS (ID, NAME, DESCRIPTION, PRICE)
    VALUES (3, 'TELEVISAO', 'TELEVISAO 50 POLEGADAS', 250.24);