INSERT INTO PRODUCTS (ID, NAME, DESCRIPTION, PRICE)
    VALUES (1, 'ABAJUR', 'ABAJUR COMUN', 12.34);
    
INSERT INTO PRODUCTS (ID, NAME, DESCRIPTION, PRICE)
    VALUES (2, 'ASPIRADOR', 'ASPIRADOR DE PO', 98.50);
    
INSERT INTO PRODUCTS (ID, NAME, DESCRIPTION, PRICE)
    VALUES (3, 'TELEVISAO 1', 'TELEVISAO 50 POLEGADAS', 250.24);
    
INSERT INTO PRODUCTS (ID, NAME, DESCRIPTION, PRICE)
    VALUES (4, 'TELEVISAO 2', 'TELEVISAO 40 POLEGADAS', 210.24);