INSERT INTO PRODUCTS (NAME, DESCRIPTION, PRICE)
    VALUES ('ABAJUR', 'ABAJUR COMUN', 12.34);
    
INSERT INTO PRODUCTS (NAME, DESCRIPTION, PRICE)
    VALUES ('ASPIRADOR', 'ASPIRADOR DE PO', 98.50);
    
INSERT INTO PRODUCTS (NAME, DESCRIPTION, PRICE)
    VALUES ('TELEVISAO 1', 'TELEVISAO 50 POLEGADAS', 250.24);
    
INSERT INTO PRODUCTS (NAME, DESCRIPTION, PRICE)
    VALUES ('TELEVISAO 2', 'TELEVISAO 40 POLEGADAS', 210.24);